#!/bin/bash
conda activate segnet && \
python train.py \
    --model SegNet \
    --dataset camvid \
    --input_size '360,480' \
    --num_workers 4 \
    --classes 11 \
    --lr 5e-4 \
    --batch_size 8 \
    --train_type train \
    --max_epochs 200 \
    --cuda True \
    # --random_mirror \
    # --random_scale \
    # --optim \cd
    # --lr_schedule \
    # --num_cycles \
    # --poly_exp \
    # --warmup_iters \
    # --warmup_factor \
    # --use_label_smoothing \
    # --use_ohem \
    # --use_lovaszsoftmax \
    # --use_focal \
    # --gpus \
    # --resume \
    # --logFile \
    # --savedir ./checkpoint/
